import { useMemo, useState } from 'react'
import { contacts } from '../data/contacts'
import { documents } from '../data/documents'
import { kpis, debt } from '../data/budget'
import { leadership } from '../data/leadership'
import { news } from '../data/news'
import { structure } from '../data/structure'
import { DocumentTable, LeaderCard, NewsCard, StructureCard } from '../components/domain'
import { BudgetChart, Button, EmptyState, Fade, FilterPill, KpiCard, PageHero, SearchInput, SectionHeader } from '../components/ui'

export const HomePage = () => <Fade><div className='space-y-6'><PageHero title='Министерство финансов Липецкой области' description='Единый цифровой портал с сервисами, документами и бюджетной аналитикой.'/><SectionHeader title='Быстрые сервисы'/><div className='grid gap-3 md:grid-cols-3'>{['Документы','Открытый бюджет','Обращения'].map(s=><Button key={s}>{s}</Button>)}</div><SectionHeader title='Ключевые показатели'/><div className='grid gap-3 md:grid-cols-3'>{kpis.map(k=><KpiCard key={k.label} {...k}/>)}</div><SectionHeader title='Новости'/><div className='grid gap-3 md:grid-cols-3'>{news.slice(0,3).map(n=><NewsCard key={n.id} n={n}/>)}</div></div></Fade>
export const AboutPage = () => <Fade><div className='space-y-4'><PageHero title='О министерстве' description='Полномочия, функции и нормативные основы деятельности.'/><p>Министерство формирует и реализует финансовую и бюджетную политику региона.</p></div></Fade>
export const LeadershipPage = () => { const [q,setQ]=useState(''); const filtered = leadership.filter(l=>l.name.toLowerCase().includes(q.toLowerCase())||l.role.toLowerCase().includes(q.toLowerCase())); return <Fade><div className='space-y-4'><PageHero title='Руководство' description='Состав, контакты и графики личного приема.'/><SearchInput value={q} onChange={setQ} placeholder='Поиск по ФИО или должности'/><div className='grid gap-3 md:grid-cols-3'>{filtered.map(l=><LeaderCard key={l.id} l={l}/>)}</div>{!filtered.length&&<EmptyState text='Ничего не найдено'/>}</div></Fade> }
export const StructurePage = () => { const [q,setQ]=useState(''); const [type,setType]=useState('Все'); const types=['Все',...new Set(structure.map(s=>s.type))]; const filtered=useMemo(()=>structure.filter(s=>(type==='Все'||s.type===type)&&s.name.toLowerCase().includes(q.toLowerCase())),[q,type]); return <Fade><div className='space-y-4'><PageHero title='Структура' description='Подразделения и направления деятельности.'/><SearchInput value={q} onChange={setQ} placeholder='Поиск подразделения'/><div className='flex gap-2'>{types.map(t=><FilterPill key={t} label={t} active={t===type} onClick={()=>setType(t)}/>)}</div><div className='grid gap-3 md:grid-cols-3'>{filtered.map(s=><StructureCard key={s.id} s={s}/>)}</div></div></Fade> }
export const DocumentsPage = () => { const [q,setQ]=useState(''); const filtered = documents.filter(d=>d.title.toLowerCase().includes(q.toLowerCase())); return <Fade><div className='space-y-4'><PageHero title='Документы' description='Реестр НПА, приказов и методических материалов.'/><SearchInput value={q} onChange={setQ} placeholder='Поиск документа'/><DocumentTable items={filtered}/></div></Fade> }
export const BudgetPage = () => <Fade><div className='space-y-4'><PageHero title='Бюджет' description='Закон о бюджете и ключевые показатели.'/><div className='grid gap-3 md:grid-cols-3'>{kpis.map(k=><KpiCard key={k.label} {...k}/>)}</div><BudgetChart title='Инфографика доходов и расходов'/></div></Fade>
export const ExecutionPage = () => <Fade><div className='space-y-4'><PageHero title='Исполнение бюджета' description='Ежеквартальные отчеты и динамика исполнения.'/><BudgetChart title='Исполнение по кварталам'/></div></Fade>
export const DebtPage = () => <Fade><div className='space-y-4'><PageHero title='Государственный долг' description='Структура долга и документы долговой политики.'/><div className='grid gap-3 md:grid-cols-2'>{debt.map(k=><KpiCard key={k.label} {...k}/>)}</div><BudgetChart title='Структура государственного долга'/></div></Fade>
export const OpenBudgetPage = () => <Fade><div className='space-y-4'><PageHero title='Открытый бюджет' description='Бюджет для граждан и интерактивные KPI.'/><BudgetChart title='Сценарии для граждан'/></div></Fade>
export const NewsPage = () => { const [q,setQ]=useState(''); const filtered = news.filter(n=>n.title.toLowerCase().includes(q.toLowerCase())); return <Fade><div className='space-y-4'><PageHero title='Новости' description='Официальные новости и объявления министерства.'/><SearchInput value={q} onChange={setQ}/><div className='grid gap-3 md:grid-cols-3'>{filtered.map(n=><NewsCard key={n.id} n={n}/>)}</div></div></Fade> }
export const ContactsPage = () => <Fade><div className='space-y-4'><PageHero title='Контакты' description='Адрес, реквизиты и форма обратной связи.'/><div className='grid gap-3 md:grid-cols-2'><KpiCard label='Адрес' value={contacts.address}/><KpiCard label='Телефон' value={contacts.phone}/><KpiCard label='Email' value={contacts.email}/><KpiCard label='Реквизиты' value={contacts.requisites}/></div><div className='h-48 rounded-2xl bg-slate-200 p-4'>Карта-заглушка</div></div></Fade>
export const AppealsPage = () => <Fade><div className='space-y-4'><PageHero title='Обращения граждан' description='Порядок подачи обращений и ответы на частые вопросы.'/><p>Подайте обращение через электронную приемную, портал Госуслуг или лично в приемные часы.</p><Button>Подать обращение</Button></div></Fade>
